### ISSUE TITLE
ab21bp0g336-69d4

### ISSUE THREAD

**Issue by zonalimitatore** [Jieli-Tech/Android-JL_Bluetooth#1]
Ni hao.
I need to know, what chip is this, or the family kind of it. 
I can't find this code chip anywhere. 
Only in the chip digit, has this numbers. And also the logo name ( JL ab21bp0g336-69d4 ).
Xiexie

**Comment by zqjasonzhong** [comment]
Hello, 
    After query, this chip `JL ab21bp0g336-69d4`  is **AC6969D4**. 
    This repositiory is for solving Android SDK problems, please go to the corresponding firmware repositiory of our company.
    [fw-AC63_BT_SDK](https://github.com/Jieli-Tech/fw-AC63_BT_SDK)
    thansk!

**Comment by zonalimitatore** [comment]
Thank you
